spring.data.mongodb.database=movie-api-db
spring.data.mongodb.uri=mongodb+srv://somyasinghal71001:hU3E0FbBxM1ienVe@cluster0.lw3p3.mongodb.net

#spring.data.mongodb.database=${env.MONGO_DATABASE}
#spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}

 
 